In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
from google.colab import files


In [ ]:
pd.set_option('display.float_format', lambda x: '%.2f' % x)

In [ ]:
data = pd.read_csv('/content/heart.csv')
data.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   52    1   0       125   212    0        1      168      0     1.00      2   
1   53    1   0       140   203    1        0      155      1     3.10      0   
2   70    1   0       145   174    0        1      125      1     2.60      0   
3   61    1   0       148   203    0        1      161      0     0.00      2   
4   62    0   0       138   294    1        1      106      0     1.90      1   

   ca  thal  target  
0   2     3       0  
1   0     3       0  
2   0     3       0  
3   1     3       0  
4   3     2       0

***Understanding Data***


*   age     -     Age in years

*   sex     -     Gender
        1 = Male
        0 = Female

*   cp      -     Chest Pain Types
        0 = Typical Angina
        1 = Atypical Angina
        2 = Non-anginal pain
        3 = Asymptomatic

*   trestbps - Resting blood pressure (in mm Hg)

*   chol - Serum Cholestrol (in mg/dl)

*   fbs - Fasting Blood Sugar > 120 mg/dl
        1 = true
        0 = false

*   restecg - Resting ECG results
        0 = normal
        1 = abnormality ST-T wave abnormality
        2 =  Showing probable or definite left ventricular hypertrophy by Estes' criteria

*   thalach - Maximum Heart rate achieved

*   exang - Exercise induced Angina
        1 = Yes
        0 = No

*   oldpeak - ST depression induced by exercise

*   slope - Slope of Peak exercise ST
        0 = Unsloping
        1 = flat
        2 = Downslopping

*   ca - No. of Major Vessels (0-3) (Flouroscopy)

*   thal - Thalassemia
        1 = normal
        2 = fixed defect
        3 = reversable defect

*   target - Presence or absence of disease
        1 = Yes
        0 = No









***Describing Data***

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1025 entries, 0 to 1024
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1025 non-null   int64  
 1   sex       1025 non-null   int64  
 2   cp        1025 non-null   int64  
 3   trestbps  1025 non-null   int64  
 4   chol      1025 non-null   int64  
 5   fbs       1025 non-null   int64  
 6   restecg   1025 non-null   int64  
 7   thalach   1025 non-null   int64  
 8   exang     1025 non-null   int64  
 9   oldpeak   1025 non-null   float64
 10  slope     1025 non-null   int64  
 11  ca        1025 non-null   int64  
 12  thal      1025 non-null   int64  
 13  target    1025 non-null   int64  
dtypes: float64(1), int64(13)
memory usage: 112.2 KB


In [ ]:
data.shape

(1025, 14)

In [ ]:
data.describe()

age     sex      cp  trestbps    chol     fbs  restecg  thalach  \
count 1025.00 1025.00 1025.00   1025.00 1025.00 1025.00  1025.00  1025.00   
mean    54.43    0.70    0.94    131.61  246.00    0.15     0.53   149.11   
std      9.07    0.46    1.03     17.52   51.59    0.36     0.53    23.01   
min     29.00    0.00    0.00     94.00  126.00    0.00     0.00    71.00   
25%     48.00    0.00    0.00    120.00  211.00    0.00     0.00   132.00   
50%     56.00    1.00    1.00    130.00  240.00    0.00     1.00   152.00   
75%     61.00    1.00    2.00    140.00  275.00    0.00     1.00   166.00   
max     77.00    1.00    3.00    200.00  564.00    1.00     2.00   202.00   

        exang  oldpeak   slope      ca    thal  target  
count 1025.00  1025.00 1025.00 1025.00 1025.00 1025.00  
mean     0.34     1.07    1.39    0.75    2.32    0.51  
std      0.47     1.18    0.62    1.03    0.62    0.50  
min      0.00     0.00    0.00    0.00    0.00    0.00  
25%      0.00     0.00    1.00    0.00    2.00    0.00  
50%      0.00     0.80    1.00    0.00    2.00    1.00  
75%      1.00     1.80    2.00    1.00    3.00    1.00  
max      1.00     6.20    2.00    4.00    3.00    1.00

### **Data Cleaning**

***Check for null/missing/invalid/duplicated data***

In [ ]:
data.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [ ]:
data.nunique()

age          41
sex           2
cp            4
trestbps     49
chol        152
fbs           2
restecg       3
thalach      91
exang         2
oldpeak      40
slope         3
ca            5
thal          4
target        2
dtype: int64

***Check null/missing/invalid data [Columnwise]***

In [ ]:
data['sex'].nunique()

2

In [ ]:
data['cp'].unique()

array([0, 1, 2, 3])

In [ ]:
data['fbs'].unique()

array([0, 1])

In [ ]:
data['restecg'].unique()

array([1, 0, 2])

In [ ]:
data['thalach'].unique()

array([168, 155, 125, 161, 106, 122, 140, 145, 144, 116, 136, 192, 156,
       142, 109, 162, 165, 148, 172, 173, 146, 179, 152, 117, 115, 112,
       163, 147, 182, 105, 150, 151, 169, 166, 178, 132, 160, 123, 139,
       111, 180, 164, 202, 157, 159, 170, 138, 175, 158, 126, 143, 141,
       167,  95, 190, 118, 103, 181, 108, 177, 134, 120, 171, 149, 154,
       153,  88, 174, 114, 195, 133,  96, 124, 131, 185, 194, 128, 127,
       186, 184, 188, 130,  71, 137,  99, 121, 187,  97,  90, 129, 113])

In [ ]:
data['exang'].unique()

array([0, 1])

In [ ]:
data['slope'].unique()

array([2, 0, 1])

In [ ]:
data['ca'].unique()

array([2, 0, 1, 3, 4])

*Check and remove the duplicates*

In [ ]:
data.duplicated().sum()

723

In [ ]:
data.drop_duplicates(inplace = True)

*ca column refers to the number of major vessels defined by integer 0 - 3. 4 is an invalid value*

In [ ]:
data.drop(data[data['ca'] == 4].index, inplace=True)

In [ ]:
data['ca'].value_counts()

ca
0    175
1     65
2     38
3     20
Name: count, dtype: int64

In [ ]:
data['ca'] = data['ca'].replace({0:3, 1:2, 2:1, 3:0})

In [ ]:
data['ca'].value_counts()

ca
3    175
2     65
1     38
0     20
Name: count, dtype: int64

In [ ]:
data['thal'].unique()

array([3, 2, 1, 0])

In [ ]:
data['target'].unique()

array([0, 1])

### **Data Processing**

Normalize the numerical features.

Age, Blood Pressure, Cholesterol, Max Heart Rate, and Old Peak

In [ ]:
#Normalize age using Scaling to Range Technique

min_max_scaler = MinMaxScaler()
data['normalized_age'] = min_max_scaler.fit_transform(data[['ca']])
data['normalized_age']


0     0.33
1     1.00
2     1.00
3     0.67
4     0.00
      ... 
723   1.00
733   1.00
739   0.67
843   1.00
878   0.67
Name: normalized_age, Length: 298, dtype: float64

In [ ]:
#Normalize Cholesterol as

'''
  chol < 200 - 0     (Normal)
  200 <= chol <= 239 - 1 (Moderate)
  chol >= 240 - 2    (High)
'''

def normalize_chol(c):
  if c < 200:
    return 0
  elif c >= 200 and c <= 239:
    return 1
  else:
    return 2

data['normalized_chol'] = data['chol'].apply(normalize_chol)
data['normalized_chol']

0      1
1      1
2      0
3      1
4      2
      ..
723    1
733    0
739    2
843    2
878    0
Name: normalized_chol, Length: 298, dtype: int64

In [ ]:
#Normalize blood pressure as

'''
  trestbps < 120 - 0 (Normal)
  129 <= trestbps <= 129 - 1 (Elevated)
  130 <= trestbps <= 139 - 2 (Hypertension - Stage 1)
  140 <= trestbps <= 179 - 3 (Hypertension - Stage 2)
  trestbps >= 180 - 4 (Hypertensive Crisis)
'''

def normalize_bps(b):
  if b < 120:
    return 0
  elif b >= 129 and b <= 129:
    return 1
  elif b >= 130 and b <= 139:
    return 2
  elif b >= 140 and b <= 179:
    return 3
  else:
    return 4

data['normalized_trestbps'] = data['trestbps'].apply(normalize_bps)
data['normalized_trestbps']

0      4
1      3
2      3
3      3
4      2
      ..
723    4
733    0
739    4
843    3
878    4
Name: normalized_trestbps, Length: 298, dtype: int64

In [ ]:
#Normalize Heart Rate Using Z-Score as it does not contain extreme outliers and does not need clipping

scaler = StandardScaler()
data['normalized_thalach'] = scaler.fit_transform(data[['thalach']])

data['normalized_age']

0     0.33
1     1.00
2     1.00
3     0.67
4     0.00
      ... 
723   1.00
733   1.00
739   0.67
843   1.00
878   0.67
Name: normalized_age, Length: 298, dtype: float64

In [ ]:
#Normalize old peak using Z-score

data['normalized_oldpeak'] = scaler.fit_transform(data[['oldpeak']])
data['normalized_oldpeak']

0     -0.05
1      1.76
2      1.33
3     -0.91
4      0.73
       ... 
723    0.38
733   -0.39
739   -0.91
843   -0.91
878    0.30
Name: normalized_oldpeak, Length: 298, dtype: float64

### **Data Analysis**

Performed----

In [ ]:
data

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     52    1   0       125   212    0        1      168      0     1.00   
1     53    1   0       140   203    1        0      155      1     3.10   
2     70    1   0       145   174    0        1      125      1     2.60   
3     61    1   0       148   203    0        1      161      0     0.00   
4     62    0   0       138   294    1        1      106      0     1.90   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
723   68    0   2       120   211    0        0      115      0     1.50   
733   44    0   2       108   141    0        1      175      0     0.60   
739   52    1   0       128   255    0        1      161      1     0.00   
843   59    1   3       160   273    0        0      125      0     0.00   
878   54    1   0       120   188    0        1      113      0     1.40   

     slope  ca  thal  target  normalized_age  normalized_chol  \
0        2   1     3       0            0.33                1   
1        0   3     3       0            1.00                1   
2        0   3     3       0            1.00                0   
3        2   2     3       0            0.67                1   
4        1   0     2       0            0.00                2   
..     ...  ..   ...     ...             ...              ...   
723      1   3     2       1            1.00                1   
733      1   3     2       1            1.00                0   
739      2   2     3       0            0.67                2   
843      2   3     2       0            1.00                2   
878      1   2     3       0            0.67                0   

     normalized_trestbps  normalized_thalach  normalized_oldpeak  
0                      4                0.81               -0.05  
1                      3                0.24                1.76  
2                      3               -1.07                1.33  
3                      3                0.50               -0.91  
4                      2               -1.89                0.73  
..                   ...                 ...                 ...  
723                    4               -1.50                0.38  
733                    0                1.11               -0.39  
739                    4                0.50               -0.91  
843                    3               -1.07               -0.91  
878                    4               -1.59                0.30  

[298 rows x 19 columns]

In [ ]:
data.to_csv('heart.csv', index=False)
files.download('heart.csv')


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>